# Generated by Django 4.1 on 2024-06-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('car_model_name', models.CharField(max_length=120)),
                ('engine_type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=150)),
                ('avarage_fuel_efficiency', models.FloatField()),
                ('car_group', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'car_models',
            },
        ),
        migrations.RenameField(
            model_name='users',
            old_name='target_acivement_count',
            new_name='target_achievement_count',
        ),
        migrations.CreateModel(
            name='MyCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('purchase_on', models.DateField()),
                ('next_oil_change_on', models.DateField()),
                ('next_inspection_on', models.DateField()),
                ('target_fuel_efficiency', models.FloatField()),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Edrive.carmodels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Edrive.users')),
            ],
            options={
                'db_table': 'my_cars',
            },
        ),
        migrations.CreateModel(
            name='FuelRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('distance', models.FloatField()),
                ('fuel_amount', models.FloatField()),
                ('fuel_efficiency', models.FloatField()),
                ('my_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Edrive.mycars')),
            ],
            options={
                'db_table': 'fuel_records',
            },
        ),
    ]
