# Generated by Django 4.1 on 2024-07-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0009_alter_carmodels_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodels',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mycars',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
