# Generated by Django 4.1 on 2024-07-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0010_carmodels_name_manufacturers_name_mycars_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodels',
            name='name',
            field=models.CharField(default='default_name', max_length=1000),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='name',
            field=models.CharField(default='default_name', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mycars',
            name='name',
            field=models.CharField(default='default_name', max_length=1000),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='default_name', max_length=1000),
        ),
    ]
