# Generated by Django 4.1 on 2024-07-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0011_alter_carmodels_name_alter_manufacturers_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
