# Generated by Django 4.1 on 2024-07-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0012_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrecords',
            name='distance',
            field=models.FloatField(verbose_name='走行距離 (km)'),
        ),
        migrations.AlterField(
            model_name='fuelrecords',
            name='fuel_amount',
            field=models.FloatField(verbose_name='給油量 (L)'),
        ),
        migrations.AlterField(
            model_name='fuelrecords',
            name='fuel_efficiency',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='燃費 (km/L)'),
        ),
    ]
