# Generated by Django 4.1 on 2024-07-09 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0014_user_created_at_user_driver_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycars',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mycars', to=settings.AUTH_USER_MODEL),
        ),
    ]
