# Generated by Django 4.1 on 2024-07-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0015_alter_mycars_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycars',
            name='purchase_on',
            field=models.DateField(null=True),
        ),
    ]
