# Generated by Django 4.1 on 2024-07-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0016_alter_mycars_purchase_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycars',
            name='next_inspection_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mycars',
            name='next_oil_change_on',
            field=models.DateField(null=True),
        ),
    ]
