# Generated by Django 4.1 on 2024-07-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0019_alter_mycars_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodels',
            name='avarage_fuel_efficiency',
            field=models.FloatField(null=True),
        ),
    ]
