# Generated by Django 4.1 on 2024-07-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0020_alter_carmodels_avarage_fuel_efficiency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodels',
            old_name='avarage_fuel_efficiency',
            new_name='average_fuel_efficiency',
        ),
    ]
