# Generated by Django 4.1 on 2024-07-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0021_rename_avarage_fuel_efficiency_carmodels_average_fuel_efficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='licence_expiry_on',
            field=models.DateField(null=True),
        ),
    ]
