# Generated by Django 4.1 on 2024-07-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0023_alter_carmodels_car_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodels',
            name='average_fuel_efficiency',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='carmodels',
            name='car_group',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
