# Generated by Django 4.1 on 2024-07-17 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0025_alter_carmodels_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodels',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Edrive.manufacturers'),
        ),
    ]
