# Generated by Django 4.1 on 2024-07-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0028_alter_mycars_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='manufacturer_name',
            field=models.CharField(choices=[('toyota', 'トヨタ'), ('honda', 'ホンダ'), ('daihatsu', 'ダイハツ'), ('nissan', 'ニッサン')], max_length=70),
        ),
    ]
