# Generated by Django 4.1 on 2024-07-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0029_alter_manufacturers_manufacturer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodels',
            name='car_model_name',
            field=models.CharField(choices=[('AQUA', 'アクア'), ('ROOMY', 'ルーミー'), ('ALPHARD', 'アルファード'), ('RAIZE', 'ライズ'), ('N-BOX', 'エヌボックス'), ('FREED', 'フリード'), ('VEZEL', 'ヴェゼル'), ('CANBUS', 'ムーヴキャンバス'), ('Tanto', 'タント'), ('Rocky', 'ロッキー'), ('NOTE', 'ノート'), ('SERENA', 'セレナ'), ('DAYZ', 'デイズ'), ('X-TRAIL', 'エクストレイル')], max_length=120),
        ),
        migrations.AlterField(
            model_name='carmodels',
            name='color',
            field=models.CharField(choices=[('red', 'レッド'), ('blue', 'ブルー'), ('white', 'ホワイト'), ('yellow', 'イエロー'), ('pink', 'ピンク'), ('green', 'グリーン'), ('black', 'ブラック'), ('purple', 'パープル'), ('grey', 'グレー'), ('brown', 'ブラウン')], max_length=150),
        ),
        migrations.AlterField(
            model_name='carmodels',
            name='engine_type',
            field=models.CharField(choices=[('gasoline', 'ガソリン'), ('hybrid', 'ハイブリッド'), ('other', 'その他')], max_length=50),
        ),
    ]
