# Generated by Django 4.1 on 2024-07-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0030_alter_carmodels_car_model_name_alter_carmodels_color_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarModels',
            new_name='CarModel',
        ),
        migrations.RenameModel(
            old_name='EcoDriveSites',
            new_name='EcoDriveSite',
        ),
        migrations.RenameModel(
            old_name='FuelRecords',
            new_name='FuelRecord',
        ),
        migrations.RenameModel(
            old_name='Manufacturers',
            new_name='Manufacturer',
        ),
        migrations.RenameModel(
            old_name='MyCars',
            new_name='MyCar',
        ),
    ]
