# Generated by Django 4.1 on 2024-08-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0034_alter_fuelrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrecord',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
