# Generated by Django 4.1 on 2024-08-12 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0036_alter_fuelrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
