# Generated by Django 4.1 on 2024-08-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0037_fuelrecord_date_alter_fuelrecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
