# Generated by Django 4.1 on 2024-08-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0038_alter_fuelrecord_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fuelrecord',
            unique_together={('my_car', 'date')},
        ),
    ]
