# Generated by Django 4.1 on 2024-08-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edrive', '0039_alter_fuelrecord_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fuelrecord',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='fuelrecord',
            constraint=models.UniqueConstraint(fields=('my_car', 'date'), name='records_unique'),
        ),
    ]
